<?php

/*
 * This file is part of PHP CS Fixer.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *     Dariusz Rumiński <dariusz.ruminski@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace TweetProxyBundle\Repository;

/**
 * TweetsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTweetsPerUser($user_id, $limit = 20)
    {
        return $this->createQueryBuilder('tweet')
            ->where('tweet.userId = :user_id')
            ->setParameter('user_id', $user_id)
            ->setMaxResults($limit)
            ->orderBy('tweet.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function searchTweets($doctrine, $term = null, $user_id = null)
    {
        $em = $doctrine->getManager();

        $param = array();
        if ($term !== null && $user_id !== null) {
            $query = '
                SELECT tweets.*, user.username
                FROM tweets
                INNER JOIN user ON (user.id = tweets.user_id)
                WHERE MATCH (tweet) AGAINST (:term IN BOOLEAN MODE) AND user_id = :user_id
            ';
            $param['user_id'] = $user_id;
            $param['term'] = $term;
        } elseif ($term !== null) {
            $query = '
                SELECT tweets.*, user.username
                FROM tweets
                INNER JOIN user ON (user.id = tweets.user_id)
            WHERE MATCH (tweet) AGAINST (:term IN BOOLEAN MODE)
            ';
            $param['term'] = $term;
        } elseif ($user_id !== null) {
            $query = '
                SELECT tweets.*, user.username
                FROM tweets
                INNER JOIN user ON (user.id = tweets.user_id)
                WHERE user_id = :user_id';
            $param['user_id'] = $user_id;
        }

        $stmt = $em->getConnection()->prepare($query);
        foreach ($param as $key => $value) {
            $stmt->bindValue($key, $value);
        }
        $stmt->execute();

        return $stmt->fetchAll();
    }
}
